### ISSUE TITLE
ImportError: cannot import name 'LoRAAttnAddedKVProcessor' from 'diffusers.models.attention_processor' 

### ISSUE THREAD

**Issue by songyiren98** [yael-vinker/live_sketch#2]
Hello, thanks for your amazing work! I'd like to know which diffusers the project use?

**Comment by rinongal** [comment]
Hi,

I'm using 0.18.1 but I think most versions before diffusers introduced PEFT should work.

For this specific error you can also simply delete [this line](https://github.com/yael-vinker/live_sketch/blob/f45492110d57272b8b756d0411e22fa67782362f/losses.py#L6) and [this entire class](https://github.com/yael-vinker/live_sketch/blob/f45492110d57272b8b756d0411e22fa67782362f/losses.py#L184) since they are unused and just left as an example for adding new score distillation losses.
