### ISSUE TITLE
conflicting requirements in environment.yml

### ISSUE THREAD

**Issue by gnmarten** [yael-vinker/live_sketch#4]
cool tool, I would be grateful for help with the following 

environment.yml mentions
- python=3.8
- torch==1.12.1+cu116
- xformers

but upon installation on ubuntu 20.04
-  xformers requires -> pytorch=2.0.1
and
  - xformers -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0'] (although it may accept 3.8.18 when installed via pip xformers rather than conda)

I reckon torch 1 is because of diffvg. I jumped through a lot of hoops to get diffvg compiled (e.g. downgrading to gcc 7 is a must) via DIFFVG_CUDA=1 python setup.py install

script  CUDA_VISIBLE_DEVICES=0 python animate_svg.py  runs but throws this error https://github.com/BachiLi/diffvg/issues/3 and does nothing
It would be good to know what the min/max requirements exactly are. thanks in advance

**Comment by rinongal** [comment]
Hi. I can't seem to reproduce this issue.

Ubuntu 20.04, running `conda env create -f environment.yml` finishes without issue. My gcc version is 9.4.0. Did you modify the env file in any way (e.g. change channels / remove cmake)?

You don't strictly need xformers. You should be able to run things without it if you have enough VRAM (~24GB?). Just dont use the `--use_xformers` flag.

I did not test torch 2 so I can't comment on whether you strictly need torch 1.

If you get stuck with diffvg, you might be able to build on top of the [CLIPasso](https://github.com/yael-vinker/CLIPasso) docker.

**Comment by gnmarten** [comment]
thx for the clarifications. after some tinkering with the dependencies, I can confirm that this installation works indeed. From various Github comments, I had deduced that torch 1 was a must, my apologies.

This script is very VRAM-intensive though. I maxes out my GPU. Even maxes out free Google Colab T4. Finally got diffvg to work on Colab via Camenduru's recent script: https://github.com/camenduru/DiffSketcher-colab

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 1.06 MiB is free. Process 70074 has 14.71 GiB memory in use. Of the allocated memory 13.67 GiB is allocated by PyTorch, and 264.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by karansoni0419** [comment]
Dear Prof Dr. @gnmarten,

Thank you for sharing your detailed experience and environment challenges — it’s been very insightful and has helped me better understand the setup process.

I'm currently trying to get the LiveSketch + DiffVG pipeline running myself, but I’m facing a persistent error:

```
CUDA Runtime Error: operation not supported at diffvg/scene.cpp:35
```

This happens when I run `animate_svg.py` with a caption and target SVG. I’ve ensured the environment is close to what's suggested, and my GPU supports CUDA, though I suspect there might still be a mismatch (perhaps with diffvg, torch, or hardware compatibility).

If you happen to recall any additional tweaks or dependencies that helped you get past CUDA/runtime issues, I’d be very grateful for any guidance.

Thank you again for your time and for helping the community with your feedback and findings.

Warm regards,  
Karan
