### ISSUE TITLE
large optimization/ inference time

### ISSUE THREAD

**Issue by NippunSharma** [yael-vinker/live_sketch#6]
Hi, this is truly a great piece of work!
One of the things I noticed is that the inference or optimization time per video generation is pretty large (I tried an example that took about 35mins). Is this expected?

**Comment by rinongal** [comment]
Hi,

35 minutes is more or less expected, yes (we reported ~30 mimutes on an A100 in the paper).

Two things you can do to reduce this:
- If you don't need global movement you could try to run without the global path. This should cut down times in half. You *may* need a bit of extra parameter tuning for the local path if you do this.
- You can try using fewer iterations. In some cases you can get decent results even with ~500 steps.

**Comment by NippunSharma** [comment]
@rinongal Just curious to know, is this large inference time due to using diffvg at each iteration for each frame?

**Comment by rinongal** [comment]
The biggest factor is the fact that we're an optimization based approach. We're using Score Distillation Sampling (SDS), and SDS often requires many steps to converge well. You can see this for example in the original DreamFusion paper that proposed SDS, which takes 1.5 hours on 4 GPUs to render a single scene.

If we could use 10 steps and not 1000 (for example, if we had better initialization or a stronger motion signal), we'd be done in 20 seconds. Hopefully some follow up works will get us there :)

**Comment by karansoni0419** [comment]
Dear @NippunSharma and @rinongal,

Thank you so much for the very helpful discussion above — it has been encouraging to read through your insights.

It’s truly inspiring to see that you guys got the setup working. I’ve been trying to install and run the LiveSketch setup for a few weeks now but haven’t had much success yet.

I keep running into the following error while trying to run `animate_svg.py`:

```
(diffvg_env) root@vultr:/home/xyz/public_html/diffsketch# python animate_svg.py --target "svg_input/surfer0_scaled1" --caption "A surfer riding and maneuvering on waves on a surfboard." --output_folder surfer0_scaled1
/home/xyz/public_html/diffsketch/losses.py:22: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(ctx, input_tensor, gt_grad):
/home/xyz/public_html/diffsketch/losses.py:29: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, grad_scale):
Seed set to 1000
==================================================
target: svg_input/surfer0_scaled1
caption: A surfer riding and maneuvering on waves on a surfboard.
==================================================
A single frame contains 64 points
CUDA Runtime Error: operation not supported at /home/xyz/public_html/diffsketch/diffvg/scene.cpp:35
```

I’m not sure if this is a compatibility issue or something related to my setup (PyTorch, CUDA, or GPU). It’s been quite difficult to figure out the root cause on my own.

If you guys could kindly guide me — even just by sharing your environment details or any suggestions — I would be deeply grateful. I truly appreciate your time and any help you can offer.

Warm regards
